using System.Text;

namespace MangaIngestWithUpscaling.Shared.Tests.Infrastructure;

/// <summary>
/// Writes minimal ONNX models at runtime, so a test that needs <em>a</em> model does not need a
/// real one.
/// <para>
/// The shipped models are gigabytes and live in the gitignored <c>test_data/</c> directory, so a
/// test that cannot run without them only runs on a developer machine — and then silently reports
/// success everywhere else. That is not what the affected tests actually care about:
/// <see cref="OnnxSessionFactory"/>'s provider selection, the tiling path and the file-to-file
/// upscale all need a model that loads, reports an fp16 or fp32 input and produces the right output
/// shape. A few hundred generated bytes do that exactly like a real model does, so those tests run
/// everywhere, in milliseconds, and cannot quietly stop covering anything.
/// </para>
/// <para>
/// The graphs are deliberately single-operator, at the boundary of what ONNX allows, so the
/// encoding stays short enough to read and any mistake in it fails in
/// <see cref="TinyOnnxModelTests"/> rather than in whichever test happens to ask for a model.
/// </para>
/// </summary>
internal static class TinyOnnxModel
{
    /// <summary>The input name of every generated model.</summary>
    public const string InputName = "input";

    /// <summary>The output name of every generated model.</summary>
    public const string OutputName = "output";

    private const int ElementTypeFp32 = 1;
    private const int ElementTypeFp16 = 10;
    private const int ElementTypeInt64 = 7;
    private const int ElementTypeBool = 9;

    // AttributeProto
    private const int AttributeInt64 = 3;
    private const int AttributeInt64List = 8;
    private const int AttributeTypeInt = 2;
    private const int AttributeTypeInts = 7;

    // ModelProto
    private const int IrVersion = 1;

    private const int OpsetImport = 8;
    private const int Graph = 7;

    // OperatorSetIdProto
    private const int Domain = 1;

    private const int OpsetVersion = 13;

    // GraphProto
    private const int Node = 1;

    // NodeProto
    private const int NodeInput = 1;

    private const int NodeOutput = 2;

    // GraphProto
    private const int Initializer = 5;

    private const int GraphInput = 11;

    private const int GraphOutput = 12;

    // NodeProto
    private const int NodeOpType = 4;

    private const int Attribute = 5;

    // AttributeProto
    private const int AttributeName = 1;

    private const int AttributeString = 4;
    private const int AttributeType = 20;
    private const int AttributeTypeString = 3;

    // OperatorSetIdProto
    private const int OpSetVersion = 2;

    // TensorProto
    private const int TensorDims = 1;

    private const int TensorDataType = 2;
    private const int TensorName = 8;
    private const int TensorRawData = 9;

    // ValueInfoProto / TypeProto / TypeProto.Tensor
    private const int ValueInfoName = 1;

    private const int ValueInfoType = 2;
    private const int TensorType = 1;
    private const int TensorElemType = 1;

    /// <summary>
    /// Writes a model that upsamples its input by nearest-neighbour resampling: the output is
    /// (1, channels, H * <paramref name="scale"/>, W * <paramref name="scale"/>) and the values
    /// pass through unchanged. <paramref name="fp16"/> picks the element type, so the fp16 output
    /// path can be exercised without an fp16 model on disk.
    /// </summary>
    public static string WriteNearestUpscaler(
        string directory,
        int scale = 2,
        bool fp16 = true,
        string fileName = "tiny-upscaler.onnx"
    )
    {
        // scales = [1, 1, scale, scale], as the raw little-endian bytes of Resize's scale input.
        // A float is required here: BitConverter.GetBytes(int) would write 02 00 00 00, which is a
        // subnormal float rather than 2.0 — the model loads and runs, and silently outputs a
        // zero-sized tensor.
        byte[] scaleBytes = new byte[16];
        Buffer.BlockCopy(BitConverter.GetBytes(1f), 0, scaleBytes, 0, 4);
        Buffer.BlockCopy(BitConverter.GetBytes(1f), 0, scaleBytes, 4, 4);
        Buffer.BlockCopy(BitConverter.GetBytes((float)scale), 0, scaleBytes, 8, 4);
        Buffer.BlockCopy(BitConverter.GetBytes((float)scale), 0, scaleBytes, 12, 4);

        return Write(
            directory,
            fileName,
            ms =>
            {
                WriteVarintField(ms, IrVersion, 8);
                WriteMessage(
                    ms,
                    OpsetImport,
                    opset =>
                    {
                        // domain is written even though it is empty: opset_import[0] is the default
                        // domain, and an unset field would leave it undetermined rather than
                        // defaulted to "".
                        WriteString(opset, Domain, string.Empty);
                        WriteVarintField(opset, OpSetVersion, (ulong)OpsetVersion);
                    }
                );
                WriteMessage(
                    ms,
                    Graph,
                    graph =>
                    {
                        WriteMessage(
                            graph,
                            Node,
                            node =>
                            {
                                // Resize takes (X, roi, scales, sizes) and accepts exactly one of
                                // scales/sizes. An optional input is omitted by an empty entry
                                // rather than by shortening the list, so roi and sizes are empty
                                // strings and not missing.
                                WriteString(node, NodeInput, InputName);
                                WriteString(node, NodeInput, string.Empty);
                                WriteString(node, NodeInput, ScaleInputName);
                                WriteString(node, NodeInput, string.Empty);
                                WriteString(node, NodeOutput, OutputName);
                                WriteString(node, NodeOpType, "Resize");

                                WriteAttribute(node, "mode", "nearest");
                                WriteAttribute(
                                    node,
                                    "coordinate_transformation_mode",
                                    "asymmetric"
                                );
                                WriteAttribute(node, "nearest_mode", "floor");
                            }
                        );

                        WriteMessage(
                            graph,
                            Initializer,
                            tensor =>
                            {
                                WriteString(tensor, TensorName, ScaleInputName);
                                WriteVarintField(tensor, TensorDataType, ElementTypeFp32);
                                WriteVarintField(tensor, TensorDims, 4);
                                WriteBytes(tensor, TensorRawData, scaleBytes);
                            }
                        );

                        WriteValueInfo(graph, GraphInput, InputName, fp16);
                        WriteValueInfo(graph, GraphOutput, OutputName, fp16);
                    }
                );
            }
        );
    }

    /// <summary>
    /// Writes a model that returns its input unchanged. Useful where only a loadable session
    /// matters and no shape arithmetic does — provider selection, session caching and disposal.
    /// </summary>
    public static string WriteIdentity(string directory, bool fp16 = true) =>
        Write(
            directory,
            "tiny-identity.onnx",
            ms =>
            {
                WriteVarintField(ms, IrVersion, 8);
                WriteMessage(
                    ms,
                    OpsetImport,
                    opset =>
                    {
                        WriteString(opset, Domain, string.Empty);
                        WriteVarintField(opset, OpSetVersion, (ulong)OpsetVersion);
                    }
                );
                WriteMessage(
                    ms,
                    Graph,
                    graph =>
                    {
                        WriteMessage(
                            graph,
                            Node,
                            node =>
                            {
                                WriteString(node, NodeInput, InputName);
                                WriteString(node, NodeOutput, OutputName);
                                WriteString(node, NodeOpType, "Identity");
                            }
                        );
                        WriteValueInfo(graph, GraphInput, InputName, fp16);
                        WriteValueInfo(graph, GraphOutput, OutputName, fp16);
                    }
                );
            }
        );

    /// <summary>
    /// Writes a model whose output is not finite: <c>Div</c> by a zero initializer. Everything the
    /// pipeline does to catch an unusable model can then be exercised against a real ONNX Runtime
    /// session rather than against a hand-built output collection, which is what "the model returned
    /// NaN" actually is.
    /// </summary>
    /// <param name="nan">
    /// True for NaN (<c>Div(0, 0)</c>), false for +/- infinity (<c>Div(x, 0)</c>).
    /// </param>
    public static string WriteNonFiniteOutput(string directory, bool nan, bool fp16 = true)
    {
        // One element, not a scalar: a rank-0 tensor has no raw data at all. Div also requires the
        // initializer to match the input's type exactly, and fp16 is two bytes per element rather
        // than four.
        byte[] zero = fp16 ? [(byte)0, (byte)0] : [0, 0, 0, 0];

        return Write(
            directory,
            $"tiny-{(nan ? "nan" : "inf")}-{(fp16 ? "fp16" : "fp32")}.onnx",
            ms =>
            {
                WriteVarintField(ms, IrVersion, 8);
                WriteMessage(
                    ms,
                    OpsetImport,
                    opset =>
                    {
                        WriteString(opset, Domain, string.Empty);
                        WriteVarintField(opset, OpSetVersion, (ulong)OpsetVersion);
                    }
                );
                WriteMessage(
                    ms,
                    Graph,
                    graph =>
                    {
                        WriteMessage(
                            graph,
                            Node,
                            node =>
                            {
                                // 0/0 is NaN, x/0 is infinity: both are non-finite, and a consumer
                                // cannot tell them apart, so both have to be rejected.
                                WriteString(node, NodeInput, nan ? ZeroInputName : InputName);
                                WriteString(node, NodeInput, ZeroInputName);
                                WriteString(node, NodeOutput, OutputName);
                                WriteString(node, NodeOpType, "Div");
                            }
                        );

                        WriteMessage(
                            graph,
                            Initializer,
                            tensor =>
                            {
                                WriteString(tensor, TensorName, ZeroInputName);
                                WriteVarintField(
                                    tensor,
                                    TensorDataType,
                                    (ulong)(fp16 ? ElementTypeFp16 : ElementTypeFp32)
                                );
                                WriteVarintField(tensor, TensorDims, 1);
                                WriteBytes(tensor, TensorRawData, zero);
                            }
                        );

                        WriteValueInfo(graph, GraphInput, InputName, fp16);
                        WriteValueInfo(graph, GraphOutput, OutputName, fp16);
                    }
                );
            }
        );
    }

    private const string ScaleInputName = "scales";
    private const string ZeroInputName = "zero";
    private const string ReshapeShapeName = "shape";
    private const string ThresholdName = "threshold";

    // The tensor is [1, 3, height, width], so width and channels are the axes these are indexed on.
    private const int WidthAxis = 3;
    private const int ChannelsAxis = 1;

    private static void WriteInitializer(
        MemoryStream graph,
        string name,
        int elementType,
        int[] dims,
        byte[] payload
    ) =>
        WriteMessage(
            graph,
            Initializer,
            tensor =>
            {
                WriteString(tensor, TensorName, name);
                WriteVarintField(tensor, TensorDataType, (ulong)elementType);
                foreach (int dim in dims)
                {
                    WriteVarintField(tensor, TensorDims, (ulong)dim);
                }

                WriteBytes(tensor, TensorRawData, payload);
            }
        );

    private static void WriteInt64Attribute(MemoryStream node, string name, long value) =>
        WriteMessage(
            node,
            Attribute,
            attr =>
            {
                WriteString(attr, AttributeName, name);
                WriteVarintField(attr, AttributeInt64, (ulong)value);
                // The ONNX checker requires the declared type of every attribute, not just its value.
                WriteVarintField(attr, AttributeType, AttributeTypeInt);
            }
        );

    /// <summary>
    /// A repeated int64 attribute, which is how opset 13's ReduceMean takes its axes. Each value is
    /// its own field entry rather than one packed blob.
    /// </summary>
    private static void WriteInt64ListAttribute(MemoryStream node, string name, int[] values) =>
        WriteMessage(
            node,
            Attribute,
            attr =>
            {
                WriteString(attr, AttributeName, name);
                foreach (int value in values)
                {
                    WriteVarintField(attr, AttributeInt64List, (ulong)value);
                }

                WriteVarintField(attr, AttributeType, AttributeTypeInts);
            }
        );

    private static void WriteAttribute(MemoryStream node, string name, string value) =>
        WriteMessage(
            node,
            Attribute,
            attr =>
            {
                WriteString(attr, AttributeName, name);
                WriteString(attr, AttributeString, value);
                WriteVarintField(attr, AttributeType, AttributeTypeString);
            }
        );

    /// <summary>The peak-mask output name, which is the name the detector looks its result up by.</summary>
    public const string PeakMaskName = "peak_mask";

    /// <summary>The per-row score the detector reads its confidence from.</summary>
    public const string ProbabilitiesName = "probabilities";

    /// <summary>
    /// Writes a model that behaves like the page-break detector: for every input row it emits the
    /// row's mean channel value as <c>probabilities</c>, and whether that mean exceeds 0.5 as
    /// <c>peak_mask</c>. Both outputs have one entry per input row, so the detector's edge margin,
    /// its coordinate mapping back to the original image and its channel layout can be exercised
    /// against an image whose rows are known.
    /// <para>
    /// The mean is taken over width and then over channels, so it is the mean of the whole row. That
    /// makes it sensitive to the channel layout: a red-only row has a row mean of 0.2 and must not
    /// trigger, while the same value in all three channels has a mean of 0.6 and must. A layout that
    /// interleaved the channels instead of keeping a plane per channel would answer the other way
    /// round, so the pair of assertions pins the plane layout rather than just "it runs".
    /// </para>
    /// </summary>
    public static string WritePeakMaskDetector(
        string directory,
        string fileName = "tiny-detector.onnx"
    ) =>
        Write(
            directory,
            fileName,
            ms =>
            {
                WriteVarintField(ms, IrVersion, 8);
                WriteMessage(
                    ms,
                    OpsetImport,
                    opset =>
                    {
                        WriteString(opset, Domain, string.Empty);
                        WriteVarintField(opset, OpSetVersion, (ulong)OpsetVersion);
                    }
                );
                WriteMessage(
                    ms,
                    Graph,
                    graph =>
                    {
                        // rowMean = mean over width, then mean over channels: [1, 3, H, W] -> [1, 1, H, 1].
                        // Width is axis 3 in NCHW, not 2 — indexing height there reduces over rows and
                        // silently produces one number per column instead of one per row.
                        WriteMessage(
                            graph,
                            Node,
                            node =>
                            {
                                WriteString(node, NodeInput, InputName);
                                WriteString(node, NodeOutput, "mean_over_width");
                                WriteString(node, NodeOpType, "ReduceMean");
                                WriteInt64ListAttribute(node, "axes", [WidthAxis]);
                                WriteInt64Attribute(node, "keepdims", 1);
                            }
                        );
                        WriteMessage(
                            graph,
                            Node,
                            node =>
                            {
                                WriteString(node, NodeInput, "mean_over_width");
                                WriteString(node, NodeOutput, "row_mean");
                                WriteString(node, NodeOpType, "ReduceMean");
                                WriteInt64ListAttribute(node, "axes", [ChannelsAxis]);
                                WriteInt64Attribute(node, "keepdims", 1);
                            }
                        );

                        // Reshape drops the singleton dimensions so the row mean is [1, H].
                        WriteMessage(
                            graph,
                            Node,
                            node =>
                            {
                                WriteString(node, NodeInput, "row_mean");
                                WriteString(node, NodeInput, ReshapeShapeName);
                                WriteString(node, NodeOutput, ProbabilitiesName);
                                WriteString(node, NodeOpType, "Reshape");
                            }
                        );
                        WriteMessage(
                            graph,
                            Node,
                            node =>
                            {
                                WriteString(node, NodeInput, ProbabilitiesName);
                                WriteString(node, NodeInput, ThresholdName);
                                WriteString(node, NodeOutput, PeakMaskName);
                                WriteString(node, NodeOpType, "Greater");
                            }
                        );

                        WriteInitializer(
                            graph,
                            ReshapeShapeName,
                            ElementTypeInt64,
                            [2],
                            BitConverter.GetBytes(1L).Concat(BitConverter.GetBytes(-1L)).ToArray()
                        );
                        WriteInitializer(
                            graph,
                            ThresholdName,
                            ElementTypeFp32,
                            [1],
                            BitConverter.GetBytes(0.5f)
                        );

                        WriteValueInfo(graph, GraphInput, InputName, fp16: false);
                        WriteValueInfo(graph, GraphOutput, PeakMaskName, fp16: false, asBool: true);
                        WriteValueInfo(graph, GraphOutput, ProbabilitiesName, fp16: false);
                    }
                );
            }
        );

    private static void WriteValueInfo(
        MemoryStream graph,
        int field,
        string name,
        bool fp16,
        bool asBool = false
    ) =>
        WriteMessage(
            graph,
            field,
            valueInfo =>
            {
                WriteString(valueInfo, ValueInfoName, name);
                WriteMessage(
                    valueInfo,
                    ValueInfoType,
                    type =>
                    {
                        WriteMessage(
                            type,
                            TensorType,
                            tensor =>
                            {
                                // A comparison op emits bool, and the declared type has to agree or
                                // the graph does not load.
                                int elementType =
                                    asBool ? ElementTypeBool
                                    : fp16 ? ElementTypeFp16
                                    : ElementTypeFp32;
                                WriteVarintField(tensor, TensorElemType, (ulong)elementType);
                            }
                        );
                    }
                );
            }
        );

    private static string Write(string directory, string fileName, Action<MemoryStream> writeModel)
    {
        Directory.CreateDirectory(directory);
        using var model = new MemoryStream();
        writeModel(model);
        string path = Path.Combine(directory, fileName);
        File.WriteAllBytes(path, model.ToArray());
        return path;
    }

    private static void WriteVarint(Stream stream, ulong value)
    {
        while (value >= 0x80)
        {
            stream.WriteByte((byte)(value | 0x80));
            value >>= 7;
        }

        stream.WriteByte((byte)value);
    }

    private static void WriteVarintField(Stream stream, int field, ulong value)
    {
        WriteTag(stream, field, 0);
        WriteVarint(stream, value);
    }

    private static void WriteString(Stream stream, int field, string value)
    {
        WriteTag(stream, field, 2);
        byte[] bytes = Encoding.UTF8.GetBytes(value);
        WriteVarint(stream, (ulong)bytes.Length);
        stream.Write(bytes, 0, bytes.Length);
    }

    private static void WriteBytes(Stream stream, int field, byte[] payload)
    {
        WriteTag(stream, field, 2);
        WriteVarint(stream, (ulong)payload.Length);
        stream.Write(payload, 0, payload.Length);
    }

    private static void WriteMessage(Stream stream, int field, Action<MemoryStream> writeBody)
    {
        using var body = new MemoryStream();
        writeBody(body);
        WriteTag(stream, field, 2);
        WriteVarint(stream, (ulong)body.Length);
        body.WriteTo(stream);
    }

    private static void WriteTag(Stream stream, int field, int wireType) =>
        WriteVarint(stream, (ulong)((field << 3) | wireType));
}
