using NpgsqlTypes;
using Serilog.Sinks.PostgreSQL;
using Serilog.Sinks.PostgreSQL.ColumnWriters;

namespace MangaIngestWithUpscaling.Configuration;

/// <summary>
/// Describes the PostgreSQL <c>Logs</c> table so that the Serilog sink and
/// <see cref="Data.LoggingDbContext"/> agree on its shape. The table is created by the application
/// rather than by EF migrations because <see cref="Data.LoggingDbContext"/> deliberately excludes
/// its table from migrations.
/// </summary>
public static class PostgresLogging
{
    public const string TableName = "Logs";
    public const string SchemaName = "public";

    /// <summary>
    /// DDL matching the <c>Log</c> entity and the column writers below. The schema is qualified to
    /// match the sink's explicit <see cref="SchemaName"/>; EF queries resolve the table through the
    /// connection's <c>search_path</c>, which includes <c>public</c> by default.
    /// </summary>
    public const string CreateTableSql = """
        CREATE TABLE IF NOT EXISTS public."Logs" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Timestamp" timestamp with time zone NOT NULL,
            "Level" text NULL,
            "Exception" text NULL,
            "RenderedMessage" text NULL,
            "Properties" text NULL
        );
        """;

    public static IDictionary<string, ColumnWriterBase> ColumnWriters { get; } =
        new Dictionary<string, ColumnWriterBase>
        {
            { "Timestamp", new TimestampColumnWriter(NpgsqlDbType.TimestampTz) },
            { "Level", new LevelColumnWriter(renderAsText: true, NpgsqlDbType.Text) },
            { "Exception", new ExceptionColumnWriter(NpgsqlDbType.Text) },
            { "RenderedMessage", new RenderedMessageColumnWriter(NpgsqlDbType.Text) },
            { "Properties", new PropertiesColumnWriter(NpgsqlDbType.Text) },
        };
}
