# .github/workflows/docker-build.yml
name: Build and Push ROCm Base Image

on:
  push:
    # Trigger only when the Dockerfile is changed
    paths:
      - rocmBase.Dockerfile

jobs:
  build:
    permissions: 
        contents: read
        packages: write 
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-arch builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Generate a timestamp tag (UTC, format: YYYYMMDDHHMMSS)
      - name: Generate timestamp tag
        id: tag
        run: |
          TAG=$(date -u +"%Y%m%d%H%M%S")
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Computed tag: $TAG"

      # Build and push the Docker image for both AMD64 and ARM64 architectures
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/lolle2000la/manga-ingest-with-upscaling-base:latest-rocm
            ghcr.io/lolle2000la/manga-ingest-with-upscaling-base:${{ env.TAG }}-rocm
