name: Velopack Release

on:
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install Velopack
        run: dotnet tool install -g vpk

      - name: Add .dotnet/tools to PATH
        shell: pwsh
        run: echo "$HOME\.dotnet\tools" >> $env:GITHUB_PATH

      - name: Package with Velopack
        run: |
          $version = "${{ github.event.release.tag_name }}".TrimStart("v")
          dotnet publish MangaIngestWithUpscaling.RemoteWorker/MangaIngestWithUpscaling.RemoteWorker.csproj -c Release --self-contained -r win-x64 -p:Version=$VERSION -p:IncludeUpdater=true -o ./publish
          vpk pack --packId MangaIngestWithUpscaling.RemoteWorker --packVersion $VERSION --packDir ./publish --mainExe MangaIngestWithUpscaling.RemoteWorker


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: artifacts

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install Velopack
        run: dotnet tool install -g vpk

      - name: Add .dotnet/tools to PATH
        run: echo "/root/.dotnet/tools" >> $GITHUB_PATH

      - name: Package with Velopack
        run: |
          apt update && apt install -y squashfs-tools  
          VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')
          dotnet publish MangaIngestWithUpscaling.RemoteWorker/MangaIngestWithUpscaling.RemoteWorker.csproj -c Release --self-contained -r linux-x64 -p:Version=$VERSION -p:IncludeUpdater=true -o ./publish
          vpk pack --packId MangaIngestWithUpscaling.RemoteWorker --packVersion $VERSION --packDir ./publish --mainExe MangaIngestWithUpscaling.RemoteWorker

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: artifacts

  upload-release-assets:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    permissions:
      contents: write # needed to write releases
    steps:
      - name: Download windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-release
          path: release/win
      - name: Download linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-release
          path: release/linux
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/win/*
            release/linux/*
